### ISSUE TITLE
Draft of the sprint 1 presentation

### ISSUE THREAD

**Issue by kalgynirae** [routemaster/routemaster-web#17]
Here's what I have so far:

**Updated 2013-02-28 6:30 PM:** http://lumeh.org/files/public/cen3031/presentation-final.pdf

I'd like to add one more slide that gives a graphical illustration of which parts of the system our Sprint 1 work went toward.

We haven't written the "script" for the presentation yet.

Comments on content, wording, organization, layout, style, colors, presentations in general, life, the universe, everything, etc. are appreciated.

**Comment by kalgynirae** [comment]
I just updated the link to the presentation. We swapped the Design and Sprint 1 Goals slides.

**Comment by kalgynirae** [comment]
Updated again. I added a final slide that just says "Scrum time!", so we don't see the black screen if you accidentally click past the Scrum 1 Goals slide.

**Comment by kalgynirae** [comment]
It's also in the Google Docs folder in case my web host dies again.

**Comment by kalgynirae** [comment]
@lefrizzell Here are screenshots of the demo pages for reference:
-    http://lumeh.org/files/public/cen3031/1_login.png
-   http://lumeh.org/files/public/cen3031/2_start_end.png
-   http://lumeh.org/files/public/cen3031/3_map.png

@Iryklaunavan @Lyrencropt just tagging you guys to make sure you see the updated slides.

**Comment by bgw** [comment]
Sprint 1 is over. I'm closing this.
