### ISSUE TITLE
File not found exception from JSHint

### ISSUE THREAD

**Issue by smishra2** [routemaster/routemaster-web#23]
I did a simple git clone and tried to run mvn package on the project, but got the following build error: 

> Failed to execute goal org.mule.tools.javascript:jshint-maven-plugin:1.0-SNAPSHOT:jshint (default) on project routemaster-frontend: Execution default of goal org.mule.tools.javascript:jshint-maven-plugin:1.0-SNAPSHOT:jshint failed: java.io.FileNotFoundException: /home/sachit/UF Spring 2013/CEN3031/Git repos/frontend/dist/rhinodo/META-INF/MANIFEST.MF (No such file or directory) 

This "dist/rhinodo/META-INF" directory isn't even in the project. I don't think it's supposed to be. What am I doing wrong?

I'm running Maven 3.0.5

**Comment by kalgynirae** [comment]
I don't know what would cause this, but did you try removing the bin/ and dist/ directories and then running `maven package`?

**Comment by bgw** [comment]
@smishra2 : Is the problem still persisting? `dist/rhinodo/META-INF` should be in the project. It is a temporary file generated by (I think) [our JSHint plugin](https://github.com/mulesoft/jshint-maven-plugin).

One idea might be to move your project directory somewhere without spaces in the path. Spaces might cause an issue like this if the plugin is poorly written. Another issue might exist with Windows compatibility. Does JSHint work for other Windows users?

**Comment by smishra2** [comment]
not a problem anymore
