### ISSUE TITLE
Decide on a color scheme for our interface.

### ISSUE THREAD

**Issue by kalgynirae** [routemaster/routemaster-web#3]
While working on making a base template, I put together this draft color scheme. The background is light gray. There's a darker gray background that can be used to highlight sections of text, and optional green and red backgrounds that can be used to highlight success and error messages. I didn't put them in the image, but I'm thinking our buttons can be the same blue color as the header. or green. or gray.

![routemaster_color_scheme](https://f.cloud.github.com/assets/1088389/141750/0844437a-7268-11e2-889c-ed11e92230d5.png)

Good? Not good? Comments?

**Comment by bgw** [comment]
**Yes. This. A thousand times this.** It looks good on my external monitor, my macbook's internal screen, and my phone. The padding is off, but I love the colors. We should probably play around with border styles, `border-radius`, and the like to turn the green, gray, and red blocks into bubbles though.

We also need to decide on fonts. [Source Sans Pro](https://www.google.com/webfonts/specimen/Source+Sans+Pro) is typically my go-to font for this type of stuff. It comes in _tons_ of different weights, and even has [a fixed-width variant](https://www.google.com/webfonts/specimen/Source+Code+Pro). Another alternative is [Droid Sans](https://www.google.com/webfonts/specimen/Droid+Sans) and [Droid Sans Mono](https://www.google.com/webfonts/specimen/Droid+Sans+Mono), which is what I think most Android applications use. Maybe we should use Source Code Pro for iOS, and Droid Sans for Android?

**Comment by bgw** [comment]
It might make sense to look at the coloring of [Mapquest Open's tiles](http://open.mapquest.com/) (when heavily zoomed in), because that's the tile-server we're most likely to end up using. That said, don't depend on the colors too heavily, because we could switch providers later. Some (paid) providers will even let you [pick your own colors](http://cloudmade.com/products/style-editor)!

![Selection_111](https://f.cloud.github.com/assets/180404/141784/fee1829a-726f-11e2-9931-35f7bde20113.png)

**Comment by sternJosh** [comment]
Looks gud. Verynice!

**Comment by kalgynirae** [comment]
I think this is good enough to get us started. Here's a screenshot of what the sample HTML currently produces:

![routemaster-base-html-screenshot](https://f.cloud.github.com/assets/1088389/142187/86b9e1ee-72cf-11e2-81a2-ddffc3731c48.png)

It's using Source Sans Pro. Right now the CSS just `@import`s it from Google's font service.

I think I'd like the map to extend all the way to the edges (like the background for the green section does), but I didn't feel like cropping a larger image. It should be easy to do that with the real map, though.

@PiPeep I actually like the blocks not being bubbles. But we can tweak that later.

**Comment by kalgynirae** [comment]
And, uh, here's a sample of the new CSS:

[![http://instacod.es/60614](http://instacod.es/file/60614)](http://instacod.es/60614)
