### ISSUE TITLE
Sharing Model with JSON

### ISSUE THREAD

**Issue by lefrizzell** [routemaster/routemaster-web#34]
@Lyrencropt and I are working on our task and have some questions:
- Does the user model hold all the fields of each user? (like friends, paths, etc.) and if so how does that tie in to friend.js that you added yesterday?
- Is user the root for all the views? (is all the data pulled from user?)
- Where does this go? A separate file or does it matter?
  Thanks

**Comment by bgw** [comment]
> @Lyrencropt and I are working on our task and have some questions:

Okay!

> - Does the user model hold all the fields of each user? (like friends, paths, etc.) and if so how does that tie in to friend.js that you added yesterday?

The model will hold the data from the database (look at Colin's code). Those are sometimes configured via the `get()` and `set()` functions in `Backbone.Model`, or in our case, via the JSON API. We separate out models into different files when we have a clear separation in functionality. Right now it's looking like each tab will have at least one module (file). Separating things into different modules is pretty much arbitrary. I haven't really looked at `friend.js` so I can't comment on that specifically.

> - Is user the root for all the views? (is all the data pulled from user?)

No. It is a subview managed by `urlHandler.js`. The User view and model should probably be configured there in the appropriate callback function(s).

> - Where does this go? A separate file or does it matter?

Again, divide things up into separate modules when you have a clear separation of functionality. As a rule of thumb, modules shouldn't be larger than about 200 lines of code, or less than about 50 lines. (Although that's not a hard rule)

> Thanks

You're welcome!

**Comment by lefrizzell** [comment]
ok we have met again and have more questions:
- we looked at the three of these: http://blog.joelberghoff.com/2012/07/22/backbone-js-tutorial-part-1/  ...we're not sure how we access the JSON, he accesses it directly on his computer. How does it come from the server?
- how does it get from the server? Are we already connect and need an extension? Do we have the url?
- what purpose does having a user function serve? There is no user view so we're not sure what to be doing with it
- if user is especially complex, we could try to do something for friends or leaders, we feel like we've read enough to have a basic understanding but we aren't sure what to specifically do
- thanks
  ![peilfAh](https://f.cloud.github.com/assets/3361801/347834/08053a48-9efc-11e2-92c2-459778024210.jpg)
